import localFont from "next/font/local";
import "./globals.css";
import "./fonts/font.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import Drawer from "./components/drawer/Drawer";
import Backdop from "./components/backdrop/Backdrop";
import Provider from "@/context/Provider";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Samin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <Provider>
        <body className="max-w-screen overflow-x-hidden">
          <div>
            <Drawer/>
            <Backdop/>
          </div>
          <Header />
          {children}
          <Footer/>
        </body>
      </Provider>
    </html>
  );
}
